### PR TITLE
Rails now returns the models embedded with associations

### PR DESCRIPTION
**Pull request by dwrvnmnr**
Added embedded models.  Currently using include, which requires each embedded model included to be specified.  There may be an automatic method to include all models automatically.

### CODE REVIEW

**Comment by pkmitre** [comment]
Code could be DRYd up a bit be replacing

        respond_to do |format|
          format.xml { render xml: organization, 
            :include => [:mailing_address, :practice_location_address, :other_provider_identifiers,
            :taxonomy_licenses, :taxonomy_groups ]}
          format.json { render json: organization, 
            :include => [:mailing_address, :practice_location_address, :other_provider_identifiers,
            :taxonomy_licenses, :taxonomy_groups ]}
        end

with

        include = [:mailing_address, :practice_location_address, :other_provider_identifiers, :taxonomy_licenses, :taxonomy_groups ]
        respond_to do |format|
          format.xml { render xml: organization, include: include }
          format.json { render json: organization, include: include }
        end

**Comment by dwrvnmnr** [comment]
Should we make this a configuration option to make it as DRY as possible, or is that a step too far?

**Comment by pkmitre** [comment]
Don't think we need a configuration option; I like DRY code, but I also value locality: I don't want to have to look in a different file to see what's being included.

**Comment by dwrvnmnr** [comment]
Applied the underscores (totally slipped my mind during the context switch between the two applications).  Locality makes sense, thought I would ask just in case.

**Pull request merged**
